---
- name: Install lutris
  gather_facts: no
  hosts: localhost
  connection: local
  tasks:
    - name: Add repository
      apt_repository:
        repo: "ppa:lutris-team/lutris"

    - name: Install packages
      apt:
        update_cache: yes
        name:
          - lutris

    - name: Clean up
      shell: |
        rm -rf /var/lib/apt/lists/*
      args:
        warn: false
