---
- name: Install libreoffice
  gather_facts: no
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        install_recommends: yes
        name:
          - libreoffice

    - name: Clean up (1)
      apt:
        autoremove: yes
        autoclean: yes

    - name: Clean up (2)
      file:
        path: /var/lib/apt/lists/
        state: absent
