---
- name: Install kodi
  gather_facts: no
  hosts: localhost
  connection: local
  tasks:
    - name: Add repository
      apt_repository:
        repo: "ppa:team-xbmc/ppa"

    - name: Install packages
      apt:
        update_cache: yes
        name:
          - kodi

    - name: Clean up (1)
      apt:
        autoremove: yes
        autoclean: yes

    - name: Clean up (2)
      file:
        path: /var/lib/apt/lists/
        state: absent
