---
- name: Install juju
  gather_facts: no
  hosts: localhost
  connection: local
  tasks:
    - name: Add repository
      apt_repository:
        repo: "ppa:juju/stable"

    - name: Install packages
      apt:
        update_cache: yes
        name:
          - juju

    - name: Clean up
      shell: |
        rm -rf /var/lib/apt/lists/*
      args:
        warn: false
