---
- name: Install go
  gather_facts: no
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        name:
          - golang-go

    - name: Clean up
      shell: |
        rm -fv /etc/systemd/system/*.wants/*
        rm -rf /var/lib/apt/lists/*
      args:
        warn: false
