---
- name: Install firefox
  gather_facts: no
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      become: yes
      apt:
        force_apt_get: yes
        update_cache: yes
        name:
          - firefox

    - name: Clean up (1)
      become: yes
      apt:
        autoremove: yes
        autoclean: yes

    - name: Clean up (2)
      file:
        path: /var/lib/apt/lists/
        state: absent
