---
- name: Install teamviewer
  gather_facts: no
  hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb

    - name: Clean up
      shell: |
        rm -rf /var/lib/apt/lists/*
      args:
        warn: false
